baseURL = "/"
languageCode = "en-us"
title = "Cyborg_m"
theme = "terminal"

[params]
  contentTypeName = "posts"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  themeColor = "green"

[languages]
  [languages.en]
    languageName = "English"
    title = "Cyborg_m"
    subtitle = "Security Researcher :: Bug Bounty Hunter"
    owner = "Mayur Salve"
    weight = 1
    [languages.en.params]
      themeColor = "green"
      [languages.en.params.logo]
        logoText = "Cyborg_m"